### ISSUE TITLE
Wheels for 15.0.4 depend on HomeBrew

### ISSUE THREAD

**Issue by ronaldoussoren** [ssciwr/clang-format-wheel#60] opened 2022-12-19 12:56 UTC
Noticed this when updating the pre-commit hook for clang-format to the latest version:

```
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 250

dyld[45432]: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: <4E913C59-89FC-3A87-A878-6F1FAD905D38> /Users/ronald/.cache/pre-commit/repofwxj8esu/py_env-python3.9/lib/python3.9/site-packages/clang_format/data/bin/clang-format
  Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)

```

This is on a machine that does not have homebrew on it. The pre-commit hook installs the clang-format wheel from PyPI.

**Comment by dokempf** [comment] 2022-12-19 13:35
This is a duplicate of #56 The issue should be fixed for the newly releases v15.0.6. If the problem persist, please feel free to reopen.

**Closed by dokempf** 2022-12-19 13:35 UTC
